import { useEffect, useState } from "react";
import axios from "axios";

import type { NextPage } from "next";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Header from "../components/Header";
import TaskList from "../components/TaskList";

import { SubtaskProps, TaskProps } from "../src/models/models";
import TaskInput from "../components/TaskInput";

const API_URL = `${process.env.NEXT_PUBLIC_API_URL}`;

const Home: NextPage = () => {
  const [tasks, setTasks] = useState<Array<TaskProps>>([]);
  const [subtasks, setSubtasks] = useState<Array<SubtaskProps>>([]);
  const [keyID, setKeyID] = useState<Array<string>>([]);

  useEffect(() => {
    axios.get(`${API_URL}.json`).then((res) => {
      const data = res.data;
      data !== null &&
        (setTasks(Object.values(data)), setKeyID(Object.keys(data)));
    });
  }, []);

  return (
    <div>
      <Head>
        <title>to.do | task management system</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/todo.ico" />
      </Head>
      <Header />
      <main className="min-h-screen m-8 md:max-w-[80vw] md:px-0 px-4 mx-auto">
        <p className="text-5xl font-medium pb-10">Task List</p>
        <div className="">
          <TaskInput
            listType={0}
            keyID={keyID}
            tasks={tasks}
            setTasks={setTasks}
          />
        </div>
        <div className="">
          <TaskList
            tasks={tasks}
            keyID={keyID}
            subtasks={subtasks}
            setTasks={setTasks}
            setSubtasks={setSubtasks}
          />
        </div>
      </main>
      <footer className={styles.footer}>
        Powered by{" "}
        <span>
          <img className="ml-3 w-7 h-6" src="/peepo.gif" alt="Racocon" />
        </span>
      </footer>
    </div>
  );
};

export default Home;
