import type { NextPage } from "next";
import Head from "next/head";
import TaskForm from "../components/TaskForm";

import TaskList from "../components/TaskList";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Streamframe | Task Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/racocon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-row">
          <img className="mx-2 w-16 h-16" src="/racocon.ico" alt="Racocon" />
          <p className="pl-4 text-6xl font-black uppercase">Streamframe</p>
        </div>
        <p className="text-[#f39c12] text-2xl">Task Management System</p>
        <div className="py-8">
          <TaskForm />
        </div>
        <div className="border-[0.5px] w-full border-[#7f8c8d]" />
        <TaskList />
      </main>

      <footer className={styles.footer}>
        Powered by{" "}
        <span>
          <div className="flex flex-row">
            <img className="mx-2 w-6 h-5" src="/racocon.png" alt="Racocon" />
            <span>Racocon</span>
          </div>
        </span>
      </footer>
    </div>
  );
};

export default Home;
